version: '3.5'

services:
  postgres:
    container_name: postgresDb
    image: postgres
    env_file:
      - ./database.env
    volumes:
       - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - cobaDbNetwork

  mongo:
    image: mongo
    container_name: mongoDb
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 27017:27017
    networks:
      - cobaDbNetwork

networks:
  cobaDbNetwork:
    driver: bridge